from Tkinter import *
from tkMessageBox import *
import sqlite3
import os
con=sqlite3.Connection('mydbms')        #dbms connection
cur=con.cursor()

def search(p):              #function for searching a single contact
    
    if e_fname.get()!='' and e_lname.get()!='' and e_phone.get()!='' and e_dob.get()!='':               #number of queries depending upon the user's choice
        cur.execute("select * from contact_db where fname='"+e_fname.get()+"' and lname='"+e_lname.get()+"' and (phone1="+e_phone.get()+" or phone2="+e_phone.get()+" or phone3="+e_phone.get()+") and dob='"+e_dob.get()+"'")
        y=cur.fetchone()
        x=list()
        x.append(y[0].encode('utf-8'))
        x.append(y[1].encode('utf-8'))
        x.append(y[2])
        x.append(y[3])
        x.append(y[4])
        x.append(y[5].encode('utf-8'))
        x.append(y[6].encode('utf-8'))
        x.append(y[7].encode('utf-8'))
        x.append(y[8].encode('utf-8'))
        showinfo('Result',x)
    elif e_fname.get()!='' and e_lname.get()!='' and e_phone.get()!='':
        cur.execute("select * from contact_db where fname='"+e_fname.get()+"' and lname='"+e_lname.get()+"' and (phone1="+e_phone.get()+" or phone2="+e_phone.get()+" or phone3="+e_phone.get()+")")
        y=cur.fetchone()
        x=list()
        x.append(y[0].encode('utf-8'))
        x.append(y[1].encode('utf-8'))
        x.append(y[2])
        x.append(y[3])
        x.append(y[4])
        x.append(y[5].encode('utf-8'))
        x.append(y[6].encode('utf-8'))
        x.append(y[7].encode('utf-8'))
        x.append(y[8].encode('utf-8'))
        showinfo('Result',x)
    elif e_fname.get()!='' and e_lname.get()!='':
        cur.execute("select * from contact_db where fname='"+e_fname.get()+"' and lname='"+e_lname.get()+"'")
        y=cur.fetchone()
        x=list()
        x.append(y[0].encode('utf-8'))
        x.append(y[1].encode('utf-8'))
        x.append(y[2])
        x.append(y[3])
        x.append(y[4])
        x.append(y[5].encode('utf-8'))
        x.append(y[6].encode('utf-8'))
        x.append(y[7].encode('utf-8'))
        x.append(y[8].encode('utf-8'))
        showinfo('Result',x)
    elif e_fname.get()!='':
        cur.execute("select * from contact_db where fname='"+e_fname.get()+"'")
        y=cur.fetchone()
        x=list()
        x.append(y[0].encode('utf-8'))
        x.append(y[1].encode('utf-8'))
        x.append(y[2])
        x.append(y[3])
        x.append(y[4])
        x.append(y[5].encode('utf-8'))
        x.append(y[6].encode('utf-8'))
        x.append(y[7].encode('utf-8'))
        x.append(y[8].encode('utf-8'))
        showinfo('Result',x)
    elif e_lname.get()!='' and e_phone.get()!='' and e_dob.get()!='':
        cur.execute("select * from contact_db where lname='"+e_lname.get()+"' and (phone1="+e_phone.get()+" or phone2="+e_phone.get()+" or phone3="+e_phone.get()+") and dob='"+e_dob.get()+"'")
        y=cur.fetchone()
        x=list()
        x.append(y[0].encode('utf-8'))
        x.append(y[1].encode('utf-8'))
        x.append(y[2])
        x.append(y[3])
        x.append(y[4])
        x.append(y[5].encode('utf-8'))
        x.append(y[6].encode('utf-8'))
        x.append(y[7].encode('utf-8'))
        x.append(y[8].encode('utf-8'))
        showinfo('Result',x)
    elif e_phone.get()!='' and e_dob.get()!='':
        cur.execute("select * from contact_db where (phone1="+e_phone.get()+" or phone2="+e_phone.get()+" or phone3="+e_phone.get()+") and dob='"+e_dob.get()+"'")
        y=cur.fetchone()
        x=list()
        x.append(y[0].encode('utf-8'))
        x.append(y[1].encode('utf-8'))
        x.append(y[2])
        x.append(y[3])
        x.append(y[4])
        x.append(y[5].encode('utf-8'))
        x.append(y[6].encode('utf-8'))
        x.append(y[7].encode('utf-8'))
        x.append(y[8].encode('utf-8'))
        showinfo('Result',x)
    elif e_dob.get()!='':
        cur.execute("select * from contact_db where dob='"+e_dob.get()+"'")
        y=cur.fetchone()
        x=list()
        x.append(y[0].encode('utf-8'))
        x.append(y[1].encode('utf-8'))
        x.append(y[2])
        x.append(y[3])
        x.append(y[4])
        x.append(y[5].encode('utf-8'))
        x.append(y[6].encode('utf-8'))
        x.append(y[7].encode('utf-8'))
        x.append(y[8].encode('utf-8'))
        showinfo('Result',x)
    elif e_lname.get()!='':
        cur.execute("select * from contact_db where lname='"+e_lname.get()+"'")
        y=cur.fetchone()
        x=list()
        x.append(y[0].encode('utf-8'))
        x.append(y[1].encode('utf-8'))
        x.append(y[2])
        x.append(y[3])
        x.append(y[4])
        x.append(y[5].encode('utf-8'))
        x.append(y[6].encode('utf-8'))
        x.append(y[7].encode('utf-8'))
        x.append(y[8].encode('utf-8'))
        showinfo('Result',x)
    elif e_phone.get()!='':
        cur.execute("select * from contact_db where (phone1="+e_phone.get()+" or phone2="+e_phone.get()+" or phone3="+e_phone.get()+")")
        y=cur.fetchone()
        x=list()
        x.append(y[0].encode('utf-8'))
        x.append(y[1].encode('utf-8'))
        x.append(y[2])
        x.append(y[3])
        x.append(y[4])
        x.append(y[5].encode('utf-8'))
        x.append(y[6].encode('utf-8'))
        x.append(y[7].encode('utf-8'))
        x.append(y[8].encode('utf-8'))
        showinfo('Result',x)
    else:
        showerror('ERROR','Nothing to search! Please Enter some details.')          #if user makes blank search request

def view_all():         #function to see all the contacts in the memory
    cur.execute('select * from contact_db order by fname,lname')
    x=list()
    for y in cur.fetchall():
        x.append(y[0].encode('utf-8'))
        x.append(y[1].encode('utf-8'))
        x.append(y[2])
        x.append(y[3])
        x.append(y[4])
        x.append(y[5].encode('utf-8'))
        x.append(y[6].encode('utf-8'))
        x.append(y[7].encode('utf-8'))
        x.append(y[8].encode('utf-8'))
    showinfo('All contacts',x)
        
p=Tk()
p.title('View/Search')
p.iconbitmap(default='view.ico')
p.resizable(width='False',height='False')       #disables the maximize button in title bar
a=PhotoImage(file='view_main.gif')      #main image in window
label = Label(image=a,bd=10,relief='ridge').grid(row=0,columnspan=2)
Label(p,text='First Name:',font='bold').grid(row=1,column=0)
e_fname=Entry(p)
e_fname.grid(row=1,column=1)
Label(p,text='Last Name:',font='bold').grid(row=2,column=0)
e_lname=Entry(p)
e_lname.grid(row=2,column=1)
Label(p,text='Phone number:',font='bold').grid(row=3,column=0)
e_phone=Entry(p)
e_phone.grid(row=3,column=1)
Label(p,text='DoB(DD/MM/YY):',font='bold').grid(row=4,column=0)
e_dob=Entry(p)
e_dob.grid(row=4,column=1)

'''images for buttons'''
a1=PhotoImage(file='view1.gif')
label = Label(image=a1).grid(row=5,column=0)
a2=PhotoImage(file='view_all.gif')
label = Label(image=a2).grid(row=5,column=1)

Button(p,text='search',font='bold',command=lambda:search(p)).grid(row=6,column=0)
Button(p,text='View All',font='bold',command=lambda:view_all()).grid(row=6,column=1)
p.mainloop()
